# Generated by Django 5.2.3 on 2025-06-14 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VineyardGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GridCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('fungal_diseases', models.FloatField(default=0.0)),
                ('pests', models.FloatField(default=0.0)),
                ('mildew', models.FloatField(default=0.0)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='monitor.vineyardgrid')),
            ],
            options={
                'unique_together': {('grid', 'row', 'col')},
            },
        ),
    ]
