# Generated by Django 5.2.3 on 2025-06-14 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridcell',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='gridcell',
            index=models.Index(fields=['timestamp'], name='monitor_gri_timesta_e2e3c9_idx'),
        ),
    ]
