# Generated by Django 5.2.3 on 2025-06-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_gridcell_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridcell',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
