# Generated by Django 5.2.3 on 2025-06-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_gridcell_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='VineyardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('avg_fungal', models.FloatField()),
                ('avg_pests', models.FloatField()),
                ('avg_mildew', models.FloatField()),
                ('critical_areas', models.JSONField()),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='monitor_vin_timesta_dc4d71_idx')],
            },
        ),
    ]
