# Generated by Django 5.2.3 on 2025-06-14 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_vineyardstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySpray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('count', models.IntegerField(default=0)),
                ('exceeded_threshold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SprayedCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='gridcell',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gridcell',
            name='grid',
        ),
        migrations.DeleteModel(
            name='VineyardStats',
        ),
        migrations.AddIndex(
            model_name='sprayedcell',
            index=models.Index(fields=['timestamp'], name='monitor_spr_timesta_f38af2_idx'),
        ),
        migrations.AddIndex(
            model_name='sprayedcell',
            index=models.Index(fields=['x', 'y'], name='monitor_spr_x_ba96aa_idx'),
        ),
        migrations.DeleteModel(
            name='GridCell',
        ),
        migrations.DeleteModel(
            name='VineyardGrid',
        ),
    ]
