# Generated by Django 5.2.3 on 2025-06-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_dailyspray_sprayedcell_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyspray',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='dailyspray',
            name='most_sprayed_column',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyspray',
            name='spray_pattern',
            field=models.JSONField(default=dict),
        ),
    ]
